[tool.ruff]
# The same as black
line-length = 120
lint.select = [
    # pyflakes
    "F",
    # pycodestyle
    "E", "W",
    # isort
    "I",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    #flake8-pie
    "PIE",
    # flake8-quotes
    "Q",
    # flake8-simplify
    "SIM",
    # tidy imports
    "TID",
    # eradicate
    "ERA",
    # pylint
    "PLE", "PLR", "PLW",
]
lint.unfixable = ['ERA001', "E712", "T201"]
# Allow unused variables when underscore-prefixed.
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
# Assume Python 3.13.
target-version = "py313"
[tool.ruff.lint.pylint]
max-args = 8
max-statements = 60
[tool.pytest.ini_options]
pythonpath = [
  "."
]